/*************************************************************/
/*                       SCHEMA ESCOLA                      */
/*************************************************************/

/* CAUTION The command below drops a user and all owned objects. */
--DROP USER ESCO CASCADE;
CREATE USER sa IDENTIFIED BY sa;
GRANT UNLIMITED TABLESPACE TO sa;
GRANT create session to sa;

/* CREATE TABLES*/
CREATE TABLE ESCO.PESSOA
(
  id    integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nome varchar2(20),
  cpf varchar2(14)
);

CREATE TABLE ESCO.CURSO
(
  id    integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
  nome       varchar2(20)
);

CREATE TABLE ESCO.MENSALIDADE
(
  id    integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
  curso_id      integer,
  pessoa_id    integer,
  valor           number(5,2)
);

/* CREATE KEYS */
alter table ESCO.Mensalidade add constraints pessoa_fk FOREIGN KEY(pessoa_id) references ESCO.Pessoa(id);
alter table ESCO.Mensalidade add constraints curso_fk FOREIGN KEY(curso_id) references ESCO.Curso(id);

/* INSERT LINES */
Insert into ESCO.Pessoa values(1,'Eliézio Mesquita','11109865424');
Insert into ESCO.Pessoa values(2,'Maria Joaquina','93104465334');
Insert into ESCO.Pessoa values(3,'José da Silva','14109835424');

Insert into ESCO.curso values(1,'Sistemas');
Insert into ESCO.curso values(2,'Administração');
Insert into ESCO.curso values(3,'Filosofia');

Insert into ESCO.mensalidade values(1,1,1,345.45);
Insert into ESCO.mensalidade values(2,2,3,500);
Insert into ESCO.mensalidade values(3,3,2,831.28);

GRANT SELECT, UPDATE, INSERT, DELETE ON ESCO.pessoa TO ESCO;
GRANT SELECT, UPDATE, INSERT, DELETE ON ESCO.curso TO ESCO;
GRANT SELECT, UPDATE, INSERT, DELETE ON ESCO.mensalidade TO ESCO;
