-- alter session set "_ORACLE_SCRIPT"=true;
--DROP USER sa CASCADE;
CREATE USER sa IDENTIFIED BY sa;
GRANT UNLIMITED TABLESPACE TO sa;
GRANT create session to sa;
alter session set current_schema=sa;


CREATE TABLE cargo (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	nome NVARCHAR2(300) NOT NULL,
	valor number(10,2) NULL,
	CONSTRAINT cargo_nome_key UNIQUE (nome)
);
Insert into Cargo (nome,valor) values('Developer','30');
Insert into Cargo (nome,valor) values('Manager','20');


CREATE TABLE sistema (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	sigla NVARCHAR2(40) NOT NULL,
	nome NVARCHAR2(300) NOT NULL,
	descricao INTEGER NULL,
	tipo NVARCHAR2(100) NULL,
	status NVARCHAR2(15) NULL,
	custo number(10,2) NULL,
	CONSTRAINT sistema_nome_key UNIQUE (nome),
	CONSTRAINT sistema_sigla_key UNIQUE (sigla)
);

insert into sistema (sigla, nome, status) values ('coh', 'City of Heroes', 'Production');
insert into sistema (sigla, nome, status) values ('eso', 'Elder Scrolls Online', 'Production');
insert into sistema (sigla, nome, status) values ('Lotro', 'Lord of the Rings Online', 'Production');

CREATE TABLE orgao (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	sigla NVARCHAR2(40) NULL,
	nome NVARCHAR2(300) NOT NULL,
	descricao INTEGER NULL,
	logo blob NULL,
	endereco NVARCHAR2(300) NULL,
	telefone NVARCHAR2(30) NULL,
	email NVARCHAR2(120) NULL,
	nivel INTEGER NULL,
	ordem INTEGER NULL,
	parent_id INTEGER NULL,
	responsavel_id INTEGER NULL,
	CONSTRAINT orgao_nivel_check CHECK ((nivel >= 0)),
	CONSTRAINT orgao_nome_key UNIQUE (nome),
	CONSTRAINT orgao_ordem_check CHECK ((ordem >= 0))
);

insert into orgao (sigla, nome ) values ('DIRETORIA', 'Diretoria');
insert into orgao (sigla, nome ) values ('GERENCIA', 'Gernência');

CREATE TABLE papel (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	nome NVARCHAR2(300) NOT NULL,
	descricao INTEGER NULL,
	tipo INTEGER NULL,
	orgao_id INTEGER NULL,
	CONSTRAINT papel_nome_key UNIQUE (nome)
);

insert into papel (nome, orgao_id) values ('Diretor', 1);
insert into papel (nome, orgao_id) values ('Gerente', 2);
insert into papel (nome) values ('Pessoa');

CREATE TABLE pessoa (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	matricula NVARCHAR2(16) NOT NULL,
	login NVARCHAR2(100) NOT NULL,
	nome NVARCHAR2(300) NOT NULL,
	salario number(10,2) NULL,
	foto blob NULL,
	telefone NVARCHAR2(30) NULL,
	email NVARCHAR2(120) NULL,
	cargo_id INTEGER NULL,
	orgao_id INTEGER NULL,
	papel_id INTEGER NULL,
	CONSTRAINT pessoa_login_key UNIQUE (login),
	CONSTRAINT pessoa_matricula_key UNIQUE (matricula),
	CONSTRAINT pessoa_nome_key UNIQUE (nome)
);

insert into pessoa (matricula, login, nome, orgao_id) values (1, 'wdn' , 'walter' , 1 );
insert into pessoa (matricula, login, nome, orgao_id) values (2, 'rda' , 'ronda' , 2 );
insert into pessoa (matricula, login, nome, orgao_id) values (3, 'uncl' , 'Uncle Bob' , 1 );
insert into pessoa (matricula, login, nome, orgao_id) values (4, 'stv' , 'Stive Jobs' , 2 );
insert into pessoa (matricula, login, nome, orgao_id) values (5, 'bll' , 'Bill Gates' , 2 );
insert into pessoa (matricula, login, nome, orgao_id) values (6, 'mf' , 'Martin Fowler' , 1 );
insert into pessoa (matricula, login, nome, orgao_id) values (7, 'Neo' , 'Mrs Anderson' , 1 );
insert into pessoa (matricula, login, nome, orgao_id) values (8, 'gld' , 'Gilad Helkselman' , 1 );
insert into pessoa (matricula, login, nome, orgao_id) values (9, 'jk' , 'jonathan kreisberg' , 1 );
insert into pessoa (matricula, login, nome, orgao_id) values (10, 'jp' , 'Joe Pass' , 1 );
insert into pessoa (matricula, login, nome, orgao_id) values (11, 'wes' , 'Wes Montegomery' , 1 );
insert into pessoa (matricula, login, nome, orgao_id) values (12, 'john' , 'John Coltrane' , 1 );
insert into pessoa (matricula, login, nome, orgao_id) values (12, 'Miles' , 'Miles Davis' , 1 );

CREATE TABLE burnup (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	inicio date NULL,
	termino date NULL,
	iteracao INTEGER NULL,
	produzido INTEGER NULL,
	acumulado INTEGER NULL,
	esforco INTEGER NULL,
	entrega NVARCHAR2(10) NULL,
	descricao NVARCHAR2(2000) NULL,
	velocidade_pessisimista INTEGER NULL,
	velocidade_realista INTEGER NULL,
	velocidade_otimista INTEGER NULL,
	dias_sprint INTEGER NULL,
	projeto_id INTEGER NOT NULL,
	CONSTRAINT burnup_dias_sprint_check CHECK ((dias_sprint >= 0)),
	CONSTRAINT burnup_velocidade_otimista_check CHECK ((velocidade_otimista >= 0)),
	CONSTRAINT burnup_velocidade_pessisimista_check CHECK ((velocidade_pessisimista >= 0)),
	CONSTRAINT burnup_velocidade_realista_check CHECK ((velocidade_realista >= 0))
);

CREATE TABLE historia (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	nr INTEGER NULL,
	prioridade INTEGER NULL,
	pontos INTEGER NULL,
	tipo NVARCHAR2(60) NULL,
	objetivo NVARCHAR2(500) NULL,
	feature NVARCHAR2(500) NULL,
	descricao INTEGER NULL,
	status NVARCHAR2(60) NULL,
	sprint INTEGER NULL,
	demanda_id INTEGER NULL,
	projeto_id INTEGER NULL,
	CONSTRAINT historia_sprint_check CHECK ((sprint >= 0))
);

CREATE TABLE projeto (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	nome NVARCHAR2(300) NOT NULL,
	descricao INTEGER NULL,
	tipo NVARCHAR2(30) NULL,
	gitlab_id NVARCHAR2(5) NULL,
	po NVARCHAR2(300) NULL,
	prioridade INTEGER NULL,
	andamento INTEGER NULL,
	status NVARCHAR2(10) NULL,
	release INTEGER NULL,
	sprint INTEGER NULL,
	custo number(10,2) NULL,
	ultima_atualizacao timestamp default sysdate,
	planilha blob NULL,
	cordenador_id INTEGER NULL,
	demanda_id INTEGER NULL,
	lider_id INTEGER NULL,
	orgao_id INTEGER NULL,
	sistema_id INTEGER NULL,
	CONSTRAINT andamento_check CHECK ((andamento >= 0)),
	CONSTRAINT nome_key UNIQUE (nome),
	CONSTRAINT prioridade_check CHECK ((prioridade >= 0)),
	CONSTRAINT release_check CHECK ((release >= 0)),
	CONSTRAINT sprint_check CHECK ((sprint >= 0))
);

--insert into projeto (nome, andamento, prioridade, lider_id, ultima_atualizacao) values ('Guick', 10, 1 , 2, sysdate);

CREATE TABLE anotacao (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	data date NULL,
	nome NVARCHAR2(500) NULL,
	descricao INTEGER NULL,
	flag NVARCHAR2(12) NULL,
	resolvido SMALLINT NOT NULL,
	demanda_id INTEGER NULL,
	projeto_id INTEGER NOT NULL
);


CREATE TABLE time (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome nvarchar2(200),
	pessoa_id INTEGER NOT NULL,
	projeto_id INTEGER null,
	CONSTRAINT time_id_pessoa_id_621f41bb_uniq UNIQUE (id, pessoa_id)
);

CREATE TABLE risco (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	levantado date NOT NULL,
	nivel NVARCHAR2(22) NOT NULL,
	descricao NVARCHAR2(500) NULL,
	sugestao NVARCHAR2(2000) NULL,
	demanda_id INTEGER NULL,
	projeto_id INTEGER NOT NULL
);

CREATE TABLE demanda (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	nome nvarchar2(300) NOT NULL,
	tipo nvarchar2(300) NOT NULL,
	descricao INTEGER NULL,
	objetivo clob NULL,
	data_criacao timestamp NOT NULL,
	atualizado timestamp NOT NULL,
	inicio_atendimento date NULL,
	data_conclusao date NULL,
	status nvarchar2(300) NOT NULL,
	prioridade INTEGER NULL,
	fase nvarchar2(300) NULL,
	estado clob NULL,
	email nvarchar2(300) NOT NULL,
	solicitante varchar(300) NOT NULL,
	orgao_id INTEGER NULL,
	responsavel_id INTEGER NULL,
	CONSTRAINT demanda_prioridade_check CHECK ((prioridade >= 0))
);


ALTER TABLE demanda ADD CONSTRAINT demanda_orgao_id_fc57094f_fk_orgao_id FOREIGN KEY (orgao_id) REFERENCES orgao(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE demanda ADD CONSTRAINT demanda_responsavel_id_8225a805_fk_pessoa_id FOREIGN KEY (responsavel_id) REFERENCES pessoa(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE orgao ADD CONSTRAINT orgao_parent_id_8a6aa713_fk_orgao_id FOREIGN KEY (parent_id) REFERENCES orgao(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE orgao ADD CONSTRAINT orgao_responsavel_id_8a264a06_fk_pessoa_id FOREIGN KEY (responsavel_id) REFERENCES pessoa(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE papel ADD CONSTRAINT papel_orgao_id_5ab41964_fk_orgao_id FOREIGN KEY (orgao_id) REFERENCES orgao(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE pessoa ADD CONSTRAINT pessoa_cargo_id_0e1d92c6_fk_cargo_id FOREIGN KEY (cargo_id) REFERENCES cargo(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE pessoa ADD CONSTRAINT pessoa_orgao_id_87323e75_fk_orgao_id FOREIGN KEY (orgao_id) REFERENCES orgao(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE pessoa ADD CONSTRAINT pessoa_papel_id_644d94ab_fk_papel_id FOREIGN KEY (papel_id) REFERENCES papel(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE anotacao ADD CONSTRAINT anotacao_demanda_id_8ab14ee9_fk_demanda_id FOREIGN KEY (demanda_id) REFERENCES demanda(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE anotacao ADD CONSTRAINT anotacao_id_46ed0c6b_fk_id FOREIGN KEY (projeto_id) REFERENCES projeto(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE burnup ADD CONSTRAINT burnup_id_757ed0d7_fk_id FOREIGN KEY (projeto_id) REFERENCES projeto(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE historia ADD CONSTRAINT historia_demanda_id_6ecc52c3_fk_demanda_id FOREIGN KEY (demanda_id) REFERENCES demanda(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE historia ADD CONSTRAINT historia_id_f14aa6df_fk_id FOREIGN KEY (projeto_id) REFERENCES projeto(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE projeto ADD CONSTRAINT cordenador_id_19504568_fk_pessoa_id FOREIGN KEY (cordenador_id) REFERENCES pessoa(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE projeto ADD CONSTRAINT demanda_id_0d8c30f3_fk_demanda_id FOREIGN KEY (demanda_id) REFERENCES demanda(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE projeto ADD CONSTRAINT lider_id_23e54cfd_fk_pessoa_id FOREIGN KEY (lider_id) REFERENCES pessoa(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE projeto ADD CONSTRAINT orgao_id_709d9482_fk_orgao_id FOREIGN KEY (orgao_id) REFERENCES orgao(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE projeto ADD CONSTRAINT sistema_id_889b70c3_fk_sistema_id FOREIGN KEY (sistema_id) REFERENCES sistema(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE time ADD CONSTRAINT tim_id_5b489fa4_fk_ FOREIGN KEY (projeto_id) REFERENCES projeto(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE time ADD CONSTRAINT time_pessoa_id_7287ad09_fk_pessoa_id FOREIGN KEY (pessoa_id) REFERENCES pessoa(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE risco ADD CONSTRAINT risco_demanda_id_c9373785_fk_demanda_id FOREIGN KEY (demanda_id) REFERENCES demanda(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE risco ADD CONSTRAINT risco_id_a48522e7_fk_id FOREIGN KEY (projeto_id) REFERENCES projeto(id) DEFERRABLE INITIALLY DEFERRED;
